### ISSUE TITLE
fs config init

### ISSUE THREAD

**Issue by ghost** [fs/fs-tool#47]
It would be great to have `fs config init` command for creating example `.fs.yml` config in current project directory.

``` yml
servers:
  staging:
    address: user@127.0.0.1
    environment: staging
    root: /home/user/apps/project-name/current
  production:
    address: user@127.0.0.1
    environment: production
    root: /home/user/apps/project-name/current
```
